# Generated by Django 3.2 on 2021-04-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('retrieve_date', models.DateTimeField(auto_now_add=True)),
                ('authors', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('publish_date', models.DateTimeField()),
                ('href', models.URLField()),
            ],
        ),
    ]
