# Generated by Django 3.2 on 2021-04-24 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='href',
            new_name='feedurl',
        ),
    ]
