# Generated by Django 3.2 on 2021-04-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_rename_href_articles_feedurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='retrieve_date',
            field=models.DateTimeField(),
        ),
    ]
