# Generated by Django 3.2 on 2021-04-25 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0004_alter_articles_retrieve_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='retrieve_date',
        ),
    ]
