version: "3"

services:
  debug:
    build:
      dockerfile: ./Dockerfile
      context: ./
      network: host
    ports:
      - 2345:2345
    #command: "--listen=:2345 --headless=true --log=true --log-output=debugger,debuglineerr,gdbwire,lldbout,rpc --accept-multiclient --api-version=2 --check-go-version=false exec ./feedme"
    command: "--listen=:2345 --headless=true --log=true --log-output=debugger,debuglineerr,gdbwire,lldbout,rpc --accept-multiclient --api-version=2 exec /feedme"
